# Generated by Django 4.1.3 on 2022-11-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': [models.OrderBy(models.F('name'))], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
