# Generated by Django 4.1.3 on 2022-11-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_scope_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тематика', 'verbose_name_plural': 'Тематики'},
        ),
    ]
